CORR_TABLE: ../resources/FinnGen_R9_UKBB_mapping.tsv
PLINK_GENOTYPE: ../resources/1kg_EUR/EUR_phase3.filt
GLIST: ../resources/glist-hg38
SNP_TEMPLATE: ../resources/SNP_template.tsv
LD_SCORES: ../resources/ldscores.tsv
